### PR TITLE
Fix time-bound TCP calls

### PR DESCRIPTION
**Pull request by snobu**
* ModbusClient TCP calls are now time-bound via optional timeout parameter
* Added socket timeout test
* Bumped Nuget version to 1.0.4

### CODE REVIEW

**Comment by aviadmizrachi** [comment]
Thanks for the contribution

**Comment by snobu** [comment]
Can you push it to Nuget please? Thanks!

**Comment by aviadmizrachi** [comment]
Sure

I will update you once uploaded

**Comment by aviadmizrachi** [comment]
Nuget package uploaded.
Will be available after indexing (in about an hour)

Good Luck

**Comment by snobu** [comment]
Appreciated!

Love the 'Good Luck', you sir truly understand software development :)

**Pull request merged**
